### ISSUE TITLE
Option curl « --insecure » superflue et dangereuse

### ISSUE THREAD

**Issue by dClauzel** [C-Duv/freemobile-smsapi-client#2]
Le certificat TLS pour l’API `https://smsapi.free-mobile.fr` est correct. Du coup l’option `--insecure`` pour curl est inutile, mais surtout dangereuse.

**Comment by HorlogeSkynet** [comment]
J'avais remarqué cela également, entièrement d'accord 👌

**Comment by C-Duv** [comment]
Tu as raison. Mais il me semble qu'auparavant il n'était pas valide et que donc j'avais des erreurs à l’exécution.
Content qu'ils aient corrigé ça.
